### ISSUE TITLE
Error running status on Windows with latest installer

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind-installer#139]
When I try to run status with the latest installer on Windows I get:

C:\tmp>cwctl-win.exe status
2019/10/04 16:04:57 {"error":"sec_schema","error_description":"Target deployment not found"}

C:\tmp>echo %errorlevel%
1

Buildinfo for installer I pulled down is:
```
# Build date: 2019-10-04-15:48:31
build_info.url=https://download.eclipse.org/codewind/codewind-installer/master/10
build_info.linux.SHA-1=b8dff94ae0c34b10bee12598c6be75c75bcd4fca
build_info.macos.SHA-1=36ef0885769d4983f2241960077841984e6c0a9a
build_info.win.SHA-1=b46290e00b9322a29936b98cbddbaf6bb9c07e5d
```

**Comment by eharris369** [comment]
Appears to start failing between this version:
```
C:\tmp>cwctl-win-2019-10-02-1353.exe status -j
{"status":"stopped","installed-versions":[]}
```
And this version (though it gives a different error than the latest):
```
C:\tmp>cwctl-win-2019-10-03-1058.exe status -j
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x865956]

goroutine 1 [running]:
github.com/eclipse/codewind-installer/actions.StatusCommand(0xc0000dc9a0)
        /home/jenkins/agent/src/github.com/eclipse/codewind-installer/actions/status.go:29 +0x36
github.com/eclipse/codewind-installer/actions.Commands.func4(0xc0000dc9a0, 0x0, 0xc0001f5950)
        /home/jenkins/agent/src/github.com/eclipse/codewind-installer/actions/commands.go:117 +0x32
github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli.HandleAction(0x8dc040, 0x9d1580, 0xc0000dc9a0, 0xc0000dc9a0, 0x0)
        /home/jenkins/agent/src/github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli/app.go:514 +0xc5
github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli.Command.Run(0x9b097f, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x9c4684, 0x29, 0x0, ...)
        /home/jenkins/agent/src/github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli/command.go:171 +0x4ab
github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli.(*App).Run(0xc0002d61c0, 0xc0000620c0, 0x3, 0x4, 0x0, 0x0)
        /home/jenkins/agent/src/github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli/app.go:265 +0x712
github.com/eclipse/codewind-installer/actions.Commands()
        /home/jenkins/agent/src/github.com/eclipse/codewind-installer/actions/commands.go:487 +0x3f5d
main.main()
        /home/jenkins/agent/src/github.com/eclipse/codewind-installer/main.go:18 +0x2c
```
